CREATE TABLE [dbo].[Users] (
  [Id] [BIGINT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [Login] NVARCHAR(30) NOT NULL,
  [Password] NVARCHAR(30) NOT NULL,
  [Created] DATETIME2 NOT NULL,
  [Updated] DATETIME2 NOT NULL,
  [LastLogin] DATETIME2 NOT NULL
)

CREATE TABLE [dbo].[Products] (
  [Id] [BIGINT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [Name] NVARCHAR(100) NOT NULL,
  [Description] NVARCHAR(MAX) NOT NULL,
  [Created] DATETIME2 NOT NULL,
  [Updated] DATETIME2 NOT NULL
)

CREATE TABLE [dbo].[Comments] (
  [Id] [BIGINT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [Text] NVARCHAR(MAX) NOT NULL,
  [UserId] [BIGINT] NOT NULL FOREIGN KEY REFERENCES [dbo].[Users] ([Id]),
  [ProductId] [BIGINT] NOT NULL FOREIGN KEY REFERENCES [dbo].[Products] ([Id]),
  [Created] DATETIME2 NOT NULL,
  [Updated] DATETIME2 NOT NULL
)
